//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsuariosServicesTest.UsuariosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/UsuariosServices")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((this.FechaEmisionField.Equals(value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UsuariosServices.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosWS.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UsuariosServicesTest.UsuariosWS.RepetidoException), Action="http://tempuri.org/IUsuarios/CrearUsuarioRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/UsuariosServices.Errores")]
        UsuariosServicesTest.UsuariosWS.Usuario CrearUsuario(UsuariosServicesTest.UsuariosWS.Usuario usuarioACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarios/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> CrearUsuarioAsync(UsuariosServicesTest.UsuariosWS.Usuario usuarioACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        UsuariosServicesTest.UsuariosWS.Usuario ObtenerUsuario(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarios/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> ObtenerUsuarioAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        UsuariosServicesTest.UsuariosWS.Usuario ModificarUsuario(UsuariosServicesTest.UsuariosWS.Usuario usuarioAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ModificarUsuario", ReplyAction="http://tempuri.org/IUsuarios/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> ModificarUsuarioAsync(UsuariosServicesTest.UsuariosWS.Usuario usuarioAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        void EliminarUsuario(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        UsuariosServicesTest.UsuariosWS.Usuario[] ListarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/ListarUsuarios", ReplyAction="http://tempuri.org/IUsuarios/ListarUsuariosResponse")]
        System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario[]> ListarUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : UsuariosServicesTest.UsuariosWS.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<UsuariosServicesTest.UsuariosWS.IUsuarios>, UsuariosServicesTest.UsuariosWS.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UsuariosServicesTest.UsuariosWS.Usuario CrearUsuario(UsuariosServicesTest.UsuariosWS.Usuario usuarioACrear) {
            return base.Channel.CrearUsuario(usuarioACrear);
        }
        
        public System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> CrearUsuarioAsync(UsuariosServicesTest.UsuariosWS.Usuario usuarioACrear) {
            return base.Channel.CrearUsuarioAsync(usuarioACrear);
        }
        
        public UsuariosServicesTest.UsuariosWS.Usuario ObtenerUsuario(string dni) {
            return base.Channel.ObtenerUsuario(dni);
        }
        
        public System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> ObtenerUsuarioAsync(string dni) {
            return base.Channel.ObtenerUsuarioAsync(dni);
        }
        
        public UsuariosServicesTest.UsuariosWS.Usuario ModificarUsuario(UsuariosServicesTest.UsuariosWS.Usuario usuarioAModificar) {
            return base.Channel.ModificarUsuario(usuarioAModificar);
        }
        
        public System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario> ModificarUsuarioAsync(UsuariosServicesTest.UsuariosWS.Usuario usuarioAModificar) {
            return base.Channel.ModificarUsuarioAsync(usuarioAModificar);
        }
        
        public void EliminarUsuario(string dni) {
            base.Channel.EliminarUsuario(dni);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(string dni) {
            return base.Channel.EliminarUsuarioAsync(dni);
        }
        
        public UsuariosServicesTest.UsuariosWS.Usuario[] ListarUsuarios() {
            return base.Channel.ListarUsuarios();
        }
        
        public System.Threading.Tasks.Task<UsuariosServicesTest.UsuariosWS.Usuario[]> ListarUsuariosAsync() {
            return base.Channel.ListarUsuariosAsync();
        }
    }
}
